first commit
danifromecuador/old-portfolio pull request #1
Opened 2022-12-01 21:14 UTC by danifromecuador

2022-12-01 21:55 UTC, bienvenuushindi reviewed
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @danifromecuador ,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You do not have a descriptive pull request. Pull Request should have a short summary describing introduced changes in more detail. Kindly add a summary to your pull request

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-02 05:31 UTC, mgmediaweb requested changes
Hi @danifromecuador , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost3](https://user-images.githubusercontent.com/41912912/205221482-4a042c0d-2fb9-4c26-ab7e-35a7c1d4d71d.gif)

## Highlights 💯 
- Professional-looking readme file. ✔️ 
- Clear and descriptive Pull Request. ✔️ 
- Clean and tidy code. ✔️ 

## Required Changes ♻️

Kindly, I suggest you better follow the original design of Figma, there are many aspects to improve, the background, the fonts, colors and spacing, as well as the icons, I know you can do it, come on!
![image](https://user-images.githubusercontent.com/41912912/205221437-82f20a8d-cfc6-40a7-a057-39cafc603118.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 05:31 UTC, mgmediaweb commented on index.html
> +        <a href="https://github.com/danifromecuador" class="fa fa-github"></a>
I kindly suggest you to use UL/LI listings in this section, this is a good practice to ensure that the user always

2022-12-02 05:31 UTC, mgmediaweb commented on index.html
> +        <div class="rectangle"></div>
Kindly, I suggest you to use all the decorative images in the background of your page, use background-image

2022-12-02 05:31 UTC, mgmediaweb commented on index.html
> +            </div>
Kindly, I suggest you use an "A" tag with a link to the homepage

2022-12-02 05:31 UTC, mgmediaweb commented on index.html
> +    <title>Document</title>
Kindly, I always suggest you indicate the correct title of your website

2022-12-02 05:31 UTC, mgmediaweb commented on index.html
> +        <h4>LET'S CONNECT</h4>
Kindly, I suggest you follow the order of the headings, if you have only used H1, you should stick with H2, this will help a lot to the accessibility of your site (you will see it very soon)

2022-12-02 22:50 UTC, danifromecuador commented
I've re done the whole project, I think I'm understanding flexbox and how to work using divs.

2022-12-02 23:46 UTC, Felix45 requested changes
Hi @danifromecuador , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights :heavy_check_mark: 
- [ ] Implemented some of the changes from the previous reviewer :white_check_mark: 
- [ ] All linter checks are setup and passing as expected :white_check_mark: 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 23:46 UTC, Felix45 commented on index.html
> +            </div>
- [ Required ] As requested by a previous reviewer please wrap this listing of social media icons in a `ul` tag instead of the generic `div` tag also make sure that each `a` tag is wrapped in a `li` tag. Since this is a list it's best if it's wrapped in a `ul` tag, kindly rectify this.

```HTML
  <ul class="icons">
    <li> <a href="https://github.com/danifromecuador" target="_blank"><img src="github.png" alt="github icon" class="github"></a></li>
    <li><a href="https://linkedin.com/in/danifromecuador/" target="_blank"><img src="linkedin.png" alt="linkedin icon" class="linkedin"></a></li>
    <li><a href="https://twitter.com/danifromecuador" target="_blank"><img src="twitter.png" alt="twitter icon" class="twitter"></a></li>
  </ul>
```

2022-12-02 23:46 UTC, Felix45 commented on styles.css
> +}
- [ Optional ] Please consider changing this color to `#6070ff` so that your design is consistent with the Figma template provided. Please see the screenshot below to understand what I mean

## Figma template
![Template 1-Mobile-Main (1)](https://user-images.githubusercontent.com/16392046/205405947-e9c7e16e-3a21-44aa-a634-a0e2b2a7a640.png)


## Your Implementation
![Screenshot from 2022-12-03 02-22-33](https://user-images.githubusercontent.com/16392046/205405684-355fb723-9e1a-4c38-81a7-e9b7195181f7.png)

2022-12-02 23:46 UTC, Felix45 commented on styles.css
> +}
- [ Optional ] Please consider changing the background color of your webpage to `#fff` instead of `black`, this is because the background color of the Figma template provided is not `black`, please see the screenshot below for details on this.
- [ Optional ] Please consider adding the `CSS` rules below to the beginning of your `index.css` file, this will ensure that the `widths`, `margins`, and `padding` in elements remain the same across all browsers. This is highly recommended for this and future projects.
```CSS
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}
```

## Figma template
<img src="https://user-images.githubusercontent.com/16392046/205407704-4c9ac796-8a5a-4de1-a10d-5e75c68d15f5.png" width="300px" />   

## Your Implementation

<img src="https://user-images.githubusercontent.com/16392046/205408721-3b3ce33f-77e9-4270-962e-3ac5f863135f.png" width="300px" />

2022-12-03 04:09 UTC, Kamba56 approved these changes
Hi @danifromecuador , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏
## Highlights
- [x] All linters passed!👏👏👏
- [x] Great use of Github workflow!👏👏👏
- [x] Descriptive PR!👏👏👏

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 04:09 UTC, Kamba56 commented on index.html
> +</html>
- [Optional] Please use an indentation of two spaces in all your documents. This is a convention and also [best practice](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

2022-12-03 04:09 UTC, Kamba56 commented on index.html
> +        </div>
- [Optional] Consider wrapping the headline section in a `section` element instead of a `div`. This is best for HTML semantics.

2022-12-03 04:09 UTC, Kamba56 commented on index.html
> +            </div>
- [Optional] This is a portfolio about you. So your name should be the main heading of the document. Kindly wrap this in a `h1` element.

2022-12-03 17:15 UTC, merged