Finish mobile version
danifromecuador/old-portfolio pull request #3
Opened 2022-12-07 21:21 UTC by danifromecuador

In this second part of the project called My Portfolio, I'm going to add "Works" section and "About Myself" section using flexbox and CSS grid.

2022-12-09 17:19 UTC, PinkMoon25 requested changes
Hi @danifromecuador , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
linters checks :heavy_check_mark: 
Professional readme :heavy_check_mark: 
follows figma template :heavy_check_mark: 
used flexbox and grid :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 17:19 UTC, pinkmoon25 commented on index.html
> +        </ul>
- [ ] good job implementing the figma design, you have done well, however please make sure  the container of the works section is a `section` tag as it is semnatically correct, a section represents a generic content on our page and is a thematic grouping of content, typically with a heading. you can use `divs` for individual project cards.
example : 
```
<section class="works"> 
  <div class='project-card'>
  </div>
</section>
```

2022-12-09 17:19 UTC, pinkmoon25 commented on index.html
> +      </section>
- [ ] Please use a `div` or `figure` tag here for your image, that will be semantically correct a `section` is not something we use to contain an `img` tag. see [html semantics here](https://www.javatpoint.com/html5-semantics)

2022-12-09 17:19 UTC, pinkmoon25 commented on index.html
> +        <article class="project-title">Tonic</article>
- [ ] Please use a heading tag (`hx`) for the headings of your project as it is semantically correct and will help in SEO,  An `article` should make sense on its own and it should be possible to distribute it independently from the rest of the site.

Potential sources for the `<article>` element:

Forum post
Blog post
News story

2022-12-09 17:19 UTC, PinkMoon25 commented on index.html
> +        </article>
- [ ] Here we can use a ul tag with each item in a li tag, like 
```
<ul> 
 <li> </li>
 <li> </li>
 <li> </li>
</ul>
```

2022-12-09 17:19 UTC, PinkMoon25 commented on index.html
> +        </article>
- [ ] As this is a paragraph, I think using a `<p>` tag is more appropriate here, which is used to represent texts or paragraphs in a document

2022-12-09 17:19 UTC, PinkMoon25 commented on index.html
> +          </footer>
- [ ] Please use a `button` tag here instead of a `footer` tag, as this is a `button` in our page and we use `button` element for buttons
 HTML `<footer>` tag is used to define a footer for a document or a section. It is generally used in the last of the section (bottom of the page).
HTML `<footer>` tag contains information about its containing elements for example:

- author information
- contact information
- copyright information
- sitemap
- back to top links
- related documents etc.

2022-12-09 17:19 UTC, PinkMoon25 commented on index.html
> +        <div class="js-list">
- [ ] Please make sure  the container of the About section is a `section` tag as it is semnatically correct, a section represents a generic content on our page and is a thematic grouping of content, typically with a heading. Instead of a `div` tag which has no semantic meaning use a `section` tag as this is a about myself section of our page.

2022-12-09 17:19 UTC, PinkMoon25 commented on index.html
> +      </div>
- [ ] Please use a `<p> `tag for paragraphs in our page, The `<p> `tag defines a paragraph.

2022-12-09 17:19 UTC, PinkMoon25 commented on index.html
> +      <div class="connect">LET'S CONNECT</div>
- [ ] Please use a heading tag(`hx`) for representing heading or subheading texts in the document, we have` <h1>` to `<h6> `levels of heading tags available to us

2022-12-09 17:19 UTC, PinkMoon25 commented on index.html
> +        </footer>
- [ ] Please use a `button` tag here instead of a `footer` tag, as this is a `button` in our page and we use `button` element for buttons
 HTML `<footer>` tag is used to define a footer for a document or a section. It is generally used in the last of the section (bottom of the page).
HTML `<footer>` tag contains information about its containing elements for example:

- author information
- contact information
- copyright information
- sitemap
- back to top links
- related documents etc.

2022-12-09 17:19 UTC, PinkMoon25 commented on index.html
> +      <div class="line-div"></div>
- [ ] Please make sure 
1. The technology categories ("Languages", "Frameworks" and "Skills") are in a `ul`, each of them in a `li`
2. The technology in each category(e.g., "JavasScript", "HTML" and "CSS") are also a list `ul` and each of them a `li`
```
<ul class="skills">
      <li class="skill-card">
        <div class="skill-title"><div class="icon rectangle"></div> Language</div>
        <ul>
          <li>Javascript</li>
          <li>Ruby</li>
          <li>Html</li>
          <li>Css</li>
        </ul>
      </li>
```

2022-12-09 23:17 UTC, rskinnerc requested changes
Hi @danifromecuador 👋👋👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![giphy](https://user-images.githubusercontent.com/26911718/206810553-6a7c3d6d-7900-41bc-bfaa-6a2f9deb1bf3.gif)

 ## Highlights
- Linters correctly configured and passing.
- Good usage of GitHub flow

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 23:17 UTC, rskinnerc commented on index.html
> +        </a>
♻️ Good job changing the footer for a button tag as suggested by the previous reviewer. However, to make this totally correct, here you could avoid nesting a `div` inside a `button` inside an `a` tag. Even though you are applying different classes so it looks like the template, you could either use a `button` tag only or an `a` tag only:

```
<a href="#" class="your-classes">
   See Project
</a>
```

Note how you can style it as per the template using a class (your-classes in my examples)

- [x] Please replace the nested tags to make it even more correct.

2022-12-09 23:17 UTC, rskinnerc commented on index.html
> +      </ul>
[OPTIONAL] Although this is an _optional change_, I strongly recommend that you stick to the template as much as possible. Currently, you are not adding all the links listed on the template:

![image](https://user-images.githubusercontent.com/26911718/206809177-66e93fbc-01b4-4843-9d47-79e102995a8f.png)

Please consider adding them for the sake of completeness. I assure you that you will need them later.

2022-12-09 23:17 UTC, rskinnerc commented on index.html
> +    <section class="content2">
♻️ Good Job changing this to a `section` tag. However, as pointed out by the previous reviewer, a section element represents a generic standalone section of a document. Having a section immediately nested inside another section might not be the right thing. 

- [ ] Please either remove that section tag or change it to a `div`. That would make your work more semantically correct.

2022-12-09 23:17 UTC, rskinnerc commented on index.html
> +      </a>
♻️ Please check my previous comment on this matter. It is better if you make this element with only one element (a o button tags)

- [ ] Please update this button using either an `a` tag or a `button` tag. That would make it semantically moe correct.

2022-12-09 23:17 UTC, rskinnerc commented on styles.css
> +.work4 {
[OPTIONAL] Good job with your design it looks very similar to the template. I strongly recommend though, that you follow the same border width o your project cards as per the design:

![image](https://user-images.githubusercontent.com/26911718/206810028-6bcbded0-5b89-42f1-a132-b9fa1e934c46.png)

Currently, your cards have a 2px border with a different color:

![image](https://user-images.githubusercontent.com/26911718/206810132-6e62ee93-34aa-4294-9fe1-4010711a3bb9.png)

2022-12-09 23:17 UTC, rskinnerc commented on styles.css
> +body {
[OPTIONAL] Great job! Your design looks very nice. There is one thing I want to suggest. Currently, your design has a fixed width. Even though it is a mobile version, there are many mobile screen sizes. Making it with a fluid width would improve the responsiveness (For any mobile, later you will add responsiveness for wide screes) of your work.

![image](https://user-images.githubusercontent.com/26911718/206810457-604a5f80-7889-450c-a24a-03f6bcec6aa8.png)

2022-12-10 16:46 UTC, PinkMoon25 approved these changes
Hi @danifromecuador , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights
linters checks :heavy_check_mark: 
Professional readme :heavy_check_mark: 
follows figma template :heavy_check_mark: 
used flexbox and grid :heavy_check_mark: 

## Optional suggestions

_**As there is just one small issue I have marked it as optional, but please take it into consideration and fix it, as it will Improve our project.**_

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-10 16:46 UTC, PinkMoon25 commented on index.html
> +      </a>
- [ ] [OPTIONAL] I think you accidentally changed this button to _**see project**_, It is supposed to be _**get my resume**_ button here, Please fix this issue.

2022-12-10 17:02 UTC, merged