Add contact form
danifromecuador/old-portfolio pull request #4
Opened 2022-12-13 22:45 UTC by danifromecuador

Last part of the Portolio's mobile version using a form tag and flexbox

2022-12-14 22:53 UTC, huseyinbiyik requested changes
Hi @danifromecuador,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![Almost there](https://media.giphy.com/media/Rv6GGaNrRbtNConlYo/giphy.gif)

## Highlights
- Commit messages are good 👌
- The design is implemented very well. 👨‍🎨

## Required Changes ♻️
- Your job is fantastic. But we should always stick to the design provided. Check the inline comments below.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
-[OPTIONAL] To delete the part below on your Readme. That message is a note for the student.
<img width="872" alt="Screenshot 2022-12-15 at 1 51 47 AM" src="https://user-images.githubusercontent.com/25887253/207732504-01c8a578-eb6b-43f7-b846-60bd78285ba5.png">


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-14 22:53 UTC, huseyinbiyik commented on index.html
> +      <input type="text" id="text" name="name" placeholder="name:" required maxlength="30">
Good job @danifromecuador. But kindly stick to the design and fix the padding according to the Figma template.
Right now your design has 12px padding.
<img width="872" alt="Screenshot 2022-12-15 at 1 36 54 AM" src="https://user-images.githubusercontent.com/25887253/207730015-b15fde7f-01d8-4e15-b4c1-f14ebf2bd360.png">

Figma paddings are slightly different.
<img width="264" alt="Screenshot 2022-12-15 at 1 30 54 AM" src="https://user-images.githubusercontent.com/25887253/207729626-1229e842-ecd4-4b65-9fdf-61b352251fc7.png">

2022-12-14 22:53 UTC, huseyinbiyik commented on index.html
> +      <input type="email" id="email" name="email" placeholder="email:" required>
Again, kindly follow the Figma template for all padding and margins and all sizes.
Your code:
<img width="872" alt="Screenshot 2022-12-15 at 1 40 38 AM" src="https://user-images.githubusercontent.com/25887253/207730597-972d30a2-97df-4cf8-8af5-070b1b04568e.png">


Figma template:
<img width="264" alt="Screenshot 2022-12-15 at 1 31 08 AM" src="https://user-images.githubusercontent.com/25887253/207730304-5f43a46e-731a-494c-b667-31c76aae75aa.png">

2022-12-14 22:53 UTC, huseyinbiyik commented on index.html
> +      <textarea name="textarea" id="textarea" placeholder="your message here:" required maxlength="500"></textarea>
Kindly follow the design for the paddings and font size. Your font size is 17px and Figma template is 15px.

Your code has slightly different padding
<img width="872" alt="Screenshot 2022-12-15 at 1 42 44 AM" src="https://user-images.githubusercontent.com/25887253/207730925-fddb887e-40de-40df-a664-47bd80fdf0e0.png">



than the Figma template.
<img width="537" alt="Screenshot 2022-12-15 at 1 28 18 AM" src="https://user-images.githubusercontent.com/25887253/207730761-741e14c3-ed02-49ca-8141-b94ddd62512c.png">

2022-12-14 22:53 UTC, huseyinbiyik commented on index.html
> +      <button  type="submit" id="button">Get In Touch</button>
Kindly add the hover color following the color defined in Figma template.
Figma template:
<img width="329" alt="Screenshot 2022-12-15 at 1 23 29 AM" src="https://user-images.githubusercontent.com/25887253/207731495-afd73515-4b27-4d0a-bad0-5e82343f4ad5.png">

Your design:
<img width="1092" alt="Screenshot 2022-12-15 at 1 22 56 AM" src="https://user-images.githubusercontent.com/25887253/207731564-21485217-6428-4473-a430-e6e3e629a1ba.png">

2022-12-15 20:46 UTC, MaganaAsiati approved these changes
# Status: Approved [✔️](https://emojipedia.org/check-mark/)
## Hi @danifromecuador  , I'm @MaganaAsiati , your reviewer for this PR  :wave: 
Great work on making the changes requested by a previous reviewer 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


<img src="https://media2.giphy.com/media/ByeYxURXxPyptxD2ta/giphy-downsized-medium.gif"/>


## Highlights
- Descriptive pull request :heavy_check_mark:👨🏻‍💻
- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:


## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future. :+1: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
Cheers and Happy coding! 🤓 👏👏👏

2022-12-15 21:07 UTC, merged